### ISSUE TITLE
我觉的应该添加一个地址工贼的issue

### ISSUE THREAD

**Issue by albert-leiming-du** [formulahendry/955.WLB#121]
同时也应该搞一个抵制工贼的活动，把抵制工贼的条款也写到996ICU License中，这样可以防止资本家对内部的分化。

**Comment by Ayke** [comment]
抵制工贼这个行为本身就是在“工人”里找“叛徒”，你可能没意识到这种“捉内奸”行为本身就是一种分化。Naive

**Comment by ShuaiShuaiLee** [comment]
不要搞人身攻击，这是制度问题！

**Comment by xuhuang37** [comment]
底线是不举报个人，不然和文革有什么区别
