### ISSUE TITLE
邪恶的项目，鼓励告密文化

### ISSUE THREAD

**Issue by Yahasana** [formulahendry/955.WLB#122]
这是个邪恶的项目，鼓励告密文化。混账！

**Comment by AnywherePear** [comment]
公开邪恶的东西，让大家都知道．
好东西不怕曝光是不？
邪恶的告密文化来自：　共党收买了某个学生潜伏在课堂，［没有其他同学知道他的存在］老师说了什么真理拆穿了党的假话就被告密．
