### ISSUE TITLE
Ban Chinese on Github

### ISSUE THREAD

**Issue by vikaskyadav** [formulahendry/955.WLB#124]
Is there any way all the Chinese guys can be taught English? Cz you guys have started spamming github.

**Comment by haoyet** [comment]
Anyone have the right to create a repo of language of their choice.

so leave Github then, you adapt to the environment, not the other way around.

**Comment by dilfish** [comment]
这是谁家的熊孩子？

**Comment by vikaskyadav** [comment]
@dilfish 你父亲
