### ISSUE TITLE
打不开955.WLB

### ISSUE THREAD

**Issue by ninjaduan** [formulahendry/955.WLB#140]
打不开
http://feathub.com/formulahendry/955.WLB

求问怎么解决，翻墙也打不开

**Comment by fynv** [comment]
同样打不开，本身就在墙外。

**Comment by jackyzhang1989** [comment]
http://feathub.com都打不开...

**Comment by torchina** [comment]
> The same can not be opened, it is outside the wall.

聊天室 - 没有自我审查
https://gitter.im/torchina/community

Tor 浏览器 8.0.8 - 绕过gfw
https://torchina.github.io/get

**Comment by formulahendry** [comment]
目前已经可以正常打开。之前打不开可能是因为这个第三方网站（feathub.com）流量扛不住了。

**Comment by ninjaduan** [comment]
原来如此，感谢。现在已经能打开了，我还suggest了一个新的WLB名单成员。

**Comment by fynv** [comment]
是的，已经可以打开。

**Comment by IsaacXiao** [comment]
现在又打不开了
