### ISSUE TITLE
Most of the companies in U.S. 

### ISSUE THREAD

**Issue by zhaomsdemo** [formulahendry/955.WLB#156]
美国的IT公司几乎没有打卡的概念，现在H1B签证已经可以允许在中国本科大学毕业的了，如果大家有能力，英语好的话，特别在中国的外企工作过的，可以尝试下去美国的一些求职网站晒晒简历，运气好的话，最终能找到一些公司提供H1B担保的，就可以有机会过来美国这边工作。
这里的大多数公司没啥加班概念，我现在在这家公司里，早10，下午4就可以走人了，周五（其实任何时候都可以）可以在家上班。
我以前在国内的时候也试过996甚至是通宵，那时还年轻，现在我肯定熬不起的，程序员一旦过了35， 在国内就是个危险的年龄，很容易被裁。
祝国内的同行们好运吧

**Comment by formulahendry** [comment]
谢谢

**Comment by MHaoYun** [comment]
s
