### ISSUE TITLE
 脉脉【前端】【内推】【高薪】 

### ISSUE THREAD

**Issue by marialovesbeans** [formulahendry/955.WLB#157]
知名中国互联网独角兽【脉脉】，招聘前端工程师啦！（美女如云，福利待遇好，氛围轻松自由，入职送Macbook/iPhone XS，一日三餐免费，租房补贴，每年出国游，每周按摩，等等。。。）

1. 前端技术栈 React MobX Node Mongo
2. 有需要咨询的直接问我~
3. 有需要内推的可以发简历给我。
4. base地 北京（具体地点具体说）~
5. 简历可以发送到企业邮箱 xiaoyaya2222@gmail.com

**Comment by formulahendry** [comment]
脉脉是955吗？

**Comment by nuying117** [comment]
估计是996的行列里的

**Comment by formulahendry** [comment]
如果不是965的话，那就不适合放在这个 repo 里了。
Closing...
