### ISSUE TITLE
996icu已经被国内互联网公司封杀了，浏览器全打不开了，不要闹了，

### ISSUE THREAD

**Issue by CPUdream** [formulahendry/955.WLB#160]
请点击下面的链接，投票或添加新公司，我会统一处理。添加新公司请注明工作地点。如果是国内公司，请加上公司中文名（比如：`Xiaomi (小米)`），或直接用中文。

http://feathub.com/formulahendry/955.WLB

**Comment by nuying117** [comment]
什么叫不要闹了？他们有他们的方式抗争，我们没有自己的方式抗争吗？

**Comment by pigyear** [comment]
当一个社会，因为恐惧，没有人愿意发声，没有人愿意抗争，就是一个奴隶的社会。

**Comment by SiegFriedrich** [comment]
跪久了,就站不起来了. 不仅不会站,也没想过要站起来.

**Comment by mianzhiyang** [comment]
wc，不要闹了？还有这种说法？不解决问题，只解决提出问题的人？

**Comment by torchina** [comment]
聊天室 - 没有自我审查
https://gitter.im/torchina/community

Tor 浏览器 8.0.8 - 绕过gfw
https://torchina.github.io/get

**Comment by qq545305338** [comment]
懦夫

**Comment by ConAntares** [comment]
真是跪久了站不起来

**Comment by popoaichuiniu** [comment]
太可怕了，竟然有的浏览器显示根据国家法律法规打不开，这尼玛谁给的权利！！！

**Comment by zhoubhin** [comment]
> 太可怕了，竟然有的浏览器显示根据国家法律法规打不开，这尼玛谁给的权利！！！

996公司的996程序员在996工作制下封禁了996.ICU项目。真是讽刺。

**Comment by zhoubhin** [comment]
跪久了就不想起来了，而且还要指责那些想站起来的人“跪着不是挺好的嘛，你们为啥要起来呢？”

**Comment by CPUdream** [comment]
我就搞不懂了，我说这么一句diss啥了，你们中的大部分不是给钱够了就愿意996吗，又能耐回传统行业去，想不通，屏蔽996icu还不是程序猿干的，又能耐这个需求不要加
________________________________
发件人: Salvador Zhou <notifications@github.com>
发送时间: 2019年4月11日 5:43
收件人: formulahendry/955.WLB
抄送: 刘玉峰; Author
主题: Re: [formulahendry/955.WLB] 996icu已经被国内互联网公司封杀了，浏览器全打不开了，不要闹了， (#160)


跪久了就不想起来了，而且还要指责那些想站起来的人“跪着不是挺好的嘛，你们为啥要起来呢？”

―

**Comment by zhoubhin** [comment]
> 我就搞不懂了，我说这么一句diss啥了，你们中的大部分不是给钱够了就愿意996吗，又能耐回传统行业去，想不通，屏蔽996icu还不是程序猿干的，又能耐这个需求不要加
> […](#)

朋友瞧你这话说的，搞得好像只要给够钱了，让你干啥你就乐意去干似的，不如你自告奋勇给我们诸位演示一下如何？
同样都是996工作制的情况下，在诸如阿里、腾讯、华为、百度等等知名公司上班的程序员们好歹有加班费之类的补贴或者说是补偿，那么其余剩下一大堆名不见经传的小公司呢？没有加班费不说，有些老板还为自己在公司提倡和宣扬的加班文化而沾沾自喜，甚至还会觉得“员工加班就是应该的，老子出钱了你们就得给我拼命干活”，怎么就这么的牛逼呢？
不是为了反对而反对，手头上的任务没完成，自愿留下来加班也好，公司要求加班也好，这是可以接受的。把加班甚至996工作制当作常态这才是问题根源，当你每天拖着疲惫不堪的身躯下班回家，你除了睡觉别的什么都不想做，日复一日，年复一年，这种全身心投入工作而毫无个人生活的日子，朋友你真的会乐在其中？
不要说什么不要闹了这种话，程序员好歹还有能力把自己的心声和想法说出来，那么传统行业的工人呢？他们很可能连上网的渠道都非常有限，更何况他们想要在网上为自己的遭遇发声了。无论是在后厂村写字楼上班的程序员，还是在山西黑煤窑挖矿的矿工，大家都是人，不是牲口，都有保障自己应得利益的权力，都有为自己的不公平遭遇而发声的权力，那要不然大家就干脆啥也别说，就这样一直下去，直到连发声的机会也没有，如何？

**Comment by jhoneybee** [comment]
> 什么叫不要闹了？他们有他们的方式抗争，我们没有自己的方式抗争吗？

很早之前就不使用国内的浏览器,一直推荐周围的人用google ,至于国内的浏览器是什么?

**Comment by 913019218** [comment]
IE能打开，路转粉。

**Comment by CPUdream** [comment]
> 跪久了,就站不起来了. 不仅不会站,也没想过要站起来.



> > 我就搞不懂了，我说这么一句diss啥了，你们中的大部分不是给钱够了就愿意996吗，又能耐回传统行业去，想不通，屏蔽996icu还不是程序猿干的，又能耐这个需求不要加
> > […](#)
> 
> 朋友瞧你这话说的，搞得好像只要给够钱了，让你干啥你就乐意去干似的，不如你自告奋勇给我们诸位演示一下如何？
> 同样都是996工作制的情况下，在诸如阿里、腾讯、华为、百度等等知名公司上班的程序员们好歹有加班费之类的补贴或者说是补偿，那么其余剩下一大堆名不见经传的小公司呢？没有加班费不说，有些老板还为自己在公司提倡和宣扬的加班文化而沾沾自喜，甚至还会觉得“员工加班就是应该的，老子出钱了你们就得给我拼命干活”，怎么就这么的牛逼呢？
> 不是为了反对而反对，手头上的任务没完成，自愿留下来加班也好，公司要求加班也好，这是可以接受的。把加班甚至996工作制当作常态这才是问题根源，当你每天拖着疲惫不堪的身躯下班回家，你除了睡觉别的什么都不想做，日复一日，年复一年，这种全身心投入工作而毫无个人生活的日子，朋友你真的会乐在其中？
> 不要说什么不要闹了这种话，程序员好歹还有能力把自己的心声和想法说出来，那么传统行业的工人呢？他们很可能连上网的渠道都非常有限，更何况他们想要在网上为自己的遭遇发声了。无论是在后厂村写字楼上班的程序员，还是在山西黑煤窑挖矿的矿工，大家都是人，不是牲口，都有保障自己应得利益的权力，都有为自己的不公平遭遇而发声的权力，那要不然大家就干脆啥也别说，就这样一直下去，直到连发声的机会也没有，如何？

典型的嘴仗，我不和你们吵，我毕业到现在从来没有去过996，你们有能耐全不要996，全抵制呀，要行动不要嘴仗，没意义。

**Comment by expyhist** [comment]
不是正在抵制吗？你来一句不要闹。。。是不是傻?

**Comment by 1015735512** [comment]
ie和chrome都能打开，其他的国产换壳浏览器以后就卸了吧！一群垃圾

**Comment by CPUdream** [comment]
> 懦夫
有能耐不要去996，我就可以
