### ISSUE TITLE
【965公司内推】【ZOOM软视软件】base合肥苏州杭州

### ISSUE THREAD

**Issue by AJLoveChina** [formulahendry/955.WLB#174]
Zoom软视软件是标准的965公司，即早上9点到下午6点。
加班很少，同时实行弹性工作时间制。
最重要的是双休日加班给予双倍薪资！

我们目前在招聘以下的岗位，如果您愿意加入我们，可以将您的简历投递到我的邮箱。
![image](https://user-images.githubusercontent.com/11222746/55766050-58f3ff00-5aa5-11e9-984c-a961833d226e.png)

1. 系统架构师
2. 资深Java后端开发 (职位多)
3. Web前端开发工程师
4. Android开发工程师
5. C++开发工程师 (Linux/Windows/Mac)
6. VOIP开发工程师
7. Salesforce开发工程师
8. 语音售后工程师
9. 机器学习算法工程师
10. 交互设计师

不必在意岗位的要求，因为我们的技术栈很全面，只要你会的主流的技术，我们都在使用。

**Comment by formulahendry** [comment]
IPO啦，恭喜恭喜~
工作地点是？

**Comment by AJLoveChina** [comment]
> IPO啦，恭喜恭喜~

同喜同喜，不及微软大佬 大佬

**Comment by juwikuang** [comment]
zoom是美国最佳雇主排名第二

**Comment by xmqs** [comment]
想去回合肥老家了，想逃离996了

**Comment by AJLoveChina** [comment]
@xmqs 那来我们zoom啊，不说是合肥最好的公司了，top的牌面肯定是有的了。
