### ISSUE TITLE
[955公司内推] Quest珠海 招聘 .net

### ISSUE THREAD

**Issue by Evan-Yang** [formulahendry/955.WLB#177]
Please find JD as below: 
The experiences on SaaS development is negotiable. 

IF
-------------------------------------------------------
Responsibilities:
Quest is looking for software development engineers to join our team to work on the following solution: Microsoft Platform Management.
With the solution, organization can streamline management, migration, customization, and protection of your application workloads and business data on Microsoft platforms such as  Azure, O365, Exchange, SharePoint, Active Directory, and Skype for Business. 
The candidates will work on the new feature development, automation testing and bug fixing for the products in the solution. 

Essential Requirements:
- A bachelor/master degree in computer science or other related disciplines.
- Mastery of algorithm and data structure.
- 3+ years mastery of C# and object oriented concepts. C++ development skill is a plus.
- 1+ years SaaS solution development experience.
- Good in oral and written English. CET4.
- Good communication skills and team work spirit.

Preferred Qualifications:
- Experiences on Azure, AWS
- Experiences on Office365, Active Directory, Exchange and SharePoint.
- Experiences on Agile Development and Continuous Integration.

IG
-------------------------------------------------------
Responsibilities:
Quest is looking for software development staff engineers to join our team to work on the following solution: Microsoft Platform Management.
With the solution, organization can streamline management, migration, customization, and protection of your application workloads and business data on Microsoft platforms such as Azure, O365, Exchange, SharePoint, Active Directory, and Skype for Business. 
The candidates will work on the new feature development, automation testing and bug fixing for the products in the solution.
The candidates will be responsible for research and block resolving, and serve as mentor of junior developers.

Essential Requirements:
- A bachelor/master degree in computer science or other related disciplines.
- Mastery of algorithm and data structure.
- 5+ years mastery of C# and object oriented concepts. C++ development skill is a plus.
- 3+ years SaaS solution development experience.
- Experiences on software design and review, served as mentor of junior developers.
- Good in oral and written English. CET4.
- Good communication skills and team work spirit.

Preferred Qualifications:
- Experiences on Azure, AWS
- Experiences on Office365, Active Directory, Exchange and SharePoint.
- Experiences on Agile Development and Continuous Integration.

不加班，不打卡，奖金 2~4个月，商业险(含家人)，年假12天起，各种福利，单身MM介绍
有意向请回你的邮箱地址
或发邮件到：evan.yang@quest.com

**Comment by HUGY1** [comment]
珠海人民支持下
