### ISSUE TITLE
都到了为中华之崛起而写码的时期了？华为都被google给禁用安卓GSM包了，假如中国没有了安卓、没有了ios或者windows系统呢？有要搞国产操作系统的大牛么，开源个项目吧，我愿意贡献微薄之力

### ISSUE THREAD

**Issue by nelsonkuang** [formulahendry/955.WLB#209]
都到了为中华之崛起而写码的时期了？华为都被google给禁用安卓GSM包了，假如中国没有了安卓、没有了ios或者windows系统呢？有要搞国产操作系统的大牛么，开源个项目吧，我愿意贡献微薄之力

**Comment by qwas982** [comment]
你们现在对开源的一切认识均是来自于美国人的宣导.好好看看专业人士观点.https://www.oschina.net/news/106863/what-about-ear-and-asf,

 我早就说过开源不可靠,https://tieba.baidu.com/p/6138170473 辩论中已有详细解说,
 快搞中文汉字汉语编程,我15年以后就一直投身探索,在我之前还有很多前辈的投入,快看到其价值和重要性!
 
 ARM也终止华为了,
https://m.cnbeta.com/wap/view/849773.htm 
不可思议,这可是源头中的源头.麒麟处理器很快要变无源之水.幸亏华为还是risc-v的会员,不过这样看还是不可靠,毕竟还是美国/.\佬搞出来的,

看来该来的迟早会来,放弃幻想,准备战斗.
中文汉字汉语编程,重复造轮子造起来!

计算机科学,软件工业在改开买办贸工技之流崛起以来,我们是没有的,即便是到现在为止也还是零,但欧美已经发展半个多世纪.你所看到的跟计算技术相关的一切软硬件均是买来的.
要完全建立咱国的计算机科学或许才有希望吧,得回到二战时,图灵那一代人的奋斗时重新思考何为[计算]才能建立新的源头!我相信咱国可以凭人多力量大集中力量办大事将这个难点攻下来,当初造原子弹时,没有计算机,国家就召集科研队伍用算盘算出高能物理的各种方程来.
看美国人对历史以来的每位老二的态度,我认为必须要灭掉美国佬,从求生的本能考虑,先下手为强.积极迎战方是上策.

**Comment by qwas982** [comment]
分析适合中文汉字汉语的编程语言文法**和**从汉字层面能同化已有算法的理论吧.
前有996,后有中兴华为被制裁,要看到重点问题在哪里.
中文汉字汉语编程,把基本盘做大,让更多国人参与程序设计.解决就业.未来在咱国土上诞生10个华为也是指日可待.
在这个基础上设计虚拟机,模拟CPU等,以后方便用电路实现虚拟机的逻辑.

**Comment by esvvv** [comment]
> 分析适合用于中文汉字汉语的编程语言文法**和**从汉字层面能同化已有算法的理论吧.
> 前有996,后有中兴华为被制裁,要看到重点问题在哪里.
> 中文汉字汉语编程,**把基本盘做大**,让更多国人(甚至全部国人)参与程序设计.解决就业.未来在咱国土上诞生10个华为20个bat也是指日可待.发挥起咱人多力量大,集中力量办大事的优良文化传统优势.
> 在这个基础上设计虚拟机,模拟CPU等,以后方便用电路实现虚拟机的逻辑.

坚决同意，闭门造车才是未来发展的趋势。
国家应该断绝与外界的一切联系，闭关锁国，发展自己操作系统、开发自己的软件，抵制linux、windows、android等境外操作系统，坚决不使用以ARM、inter、amd等境外组织设计开发制作的芯片。
首先要做到的是，断绝一切其他语言在国内传播，一切要以中文为基础，凡是由西方传入的技术都必须抵制，首先要废除现代医学，用中国传统中医取代，然后废除高考中的自然科学，物理用八卦代替，化学用五行代替，生物用太极代替，彻底回归中华传统文化。
中国应该向朝鲜学习，朝鲜能够成为超级大国，根本原因就是其保留了自己的传统，将外来文明隔绝，彻底断绝了其他文明对其“师夷长技以制夷”，在完成中华民族的伟大复兴这条道路上，吾辈任重而道远。

**Comment by qwas982** [comment]
> > 分析适合用于中文汉字汉语的编程语言文法**和**从汉字层面能同化已有算法的理论吧.
> > 前有996,后有中兴华为被制裁,要看到重点问题在哪里.
> > 中文汉字汉语编程,**把基本盘做大**,让更多国人(甚至全部国人)参与程序设计.解决就业.未来在咱国土上诞生10个华为20个bat也是指日可待.发挥起咱人多力量大,集中力量办大事的优良文化传统优势.
> > 在这个基础上设计虚拟机,模拟CPU等,以后方便用电路实现虚拟机的逻辑.
> 
> 坚决同意，闭门造车才是未来发展的趋势。
> 国家应该断绝与外界的一切联系，闭关锁国，发展自己操作系统、开发自己的软件，抵制linux、windows、android等境外操作系统，坚决不使用以ARM、inter、amd等境外组织设计开发制作的芯片。
> 首先要做到的是，断绝一切其他语言在国内传播，一切要以中文为基础，凡是由西方传入的技术都必须抵制，首先要废除现代医学，用中国传统中医取代，然后废除高考中的自然科学，物理用八卦代替，化学用五行代替，生物用太极代替，彻底回归中华传统文化。
> 中国应该向朝鲜学习，朝鲜能够成为超级大国，根本原因就是其保留了自己的传统，将外来文明隔绝，彻底断绝了其他文明对其“师夷长技以制夷”，在完成中华民族的伟大复兴这条道路上，吾辈任重而道远。

你在这里反讽什么呢反讽?
你要这样解读这样去搞你就去呀,没人拦着你.
搞中文汉字汉语编程就是闭门造车就是断绝文明交流?你脑壳被门夹了还是被驴踢了?
14亿人就不能有别的路可走?非得去当跪族跪奴跪舔西方?
你懂什么叫**多元化**么?
无脑喷杠

**Comment by crucialize** [comment]
@qwas982 又是你这个杂种，爬！

**Comment by qwas982** [comment]
@crucialize  哎呀,比你这种死邪种好不就完了,呸,不要脸的玩意儿,沙雕瘾癌毒邪病癫娼.

**Comment by fraze-smith** [comment]
为什么日本没有用日语编程,德国没用德语编程,我们却怕被封锁,事情的根本在于中国是不是要真正履行世贸成员国义务.

**Comment by qwas982** [comment]
**为什么日本没有用日语编程,德国没用德语编程,我们却怕被封锁,**
为什么?因为已经有人回答过了,你还在重复提问,只能说你孤陋寡闻.
https://github.com/program-in-chinese
https://zhuanlan.zhihu.com/codeInChinese

"**事情的根本在于中国是不是要真正履行世贸成员国义务.**"

能说出这种话,看来还没有被毛衣战打醒,看看张维为,陈平两位教授的分析再来妄谈.

**Comment by hangsome** [comment]
不是说鸿蒙开源了嘛，快去吧

**Comment by xxllp** [comment]
沸腾了 然后彻底凉了 没有国外的一些技术估计国内某些行业要倒退10年吧

**Comment by KazDelphi** [comment]
喜死我了

**Comment by KazDelphi** [comment]
> > 分析适合用于中文汉字汉语的编程语言文法**和**从汉字层面能同化已有算法的理论吧.
> > 前有996,后有中兴华为被制裁,要看到重点问题在哪里.
> > 中文汉字汉语编程,**把基本盘做大**,让更多国人(甚至全部国人)参与程序设计.解决就业.未来在咱国土上诞生10个华为20个bat也是指日可待.发挥起咱人多力量大,集中力量办大事的优良文化传统优势.
> > 在这个基础上设计虚拟机,模拟CPU等,以后方便用电路实现虚拟机的逻辑.
> 
> 坚决同意，闭门造车才是未来发展的趋势。
> 国家应该断绝与外界的一切联系，闭关锁国，发展自己操作系统、开发自己的软件，抵制linux、windows、android等境外操作系统，坚决不使用以ARM、inter、amd等境外组织设计开发制作的芯片。
> 首先要做到的是，断绝一切其他语言在国内传播，一切要以中文为基础，凡是由西方传入的技术都必须抵制，首先要废除现代医学，用中国传统中医取代，然后废除高考中的自然科学，物理用八卦代替，化学用五行代替，生物用太极代替，彻底回归中华传统文化。
> 中国应该向朝鲜学习，朝鲜能够成为超级大国，根本原因就是其保留了自己的传统，将外来文明隔绝，彻底断绝了其他文明对其“师夷长技以制夷”，在完成中华民族的伟大复兴这条道路上，吾辈任重而道远。

intel非inter
