### ISSUE TITLE
955.WLB每周六半小时线上会议

### ISSUE THREAD

**Issue by tenvgo** [formulahendry/955.WLB#272]
主题：如何得到955.WLB的工作机会？
时间：周六10:00-10:30
微信: love9871112
加微信请备注：线上会议

**Comment by oodzchen** [comment]
什么意思？周六上班也能算955.WLB吗

**Comment by tenvgo** [comment]
> 什么意思？周六上班也能算955.WLB吗

周六不上班哈，周六线上沙龙
