### ISSUE TITLE
准备回国发展，求推荐一个好公司

### ISSUE THREAD

**Issue by wangzhenhui1992** [formulahendry/955.WLB#48]
工作四年半，准备官网回国发展，求大神内推好的公司。

### 个人网站
[https://www.soaringroad.com](https://www.soaringroad.com)

技术栈包括但不限于
### 云服务

- AWS SAA认证取得 [点击查看](https://www.certmetrics.com/amazon/public/badge.aspx?i=1&t=c&d=2019-03-02&ci=AWS00708420)
- AliCloud ACA认证取得 [点击查看](https://edu.aliyun.com/clouder/Certificate/search?type=1&num=ACA01180300014382L)

### 深度学习

- Coursra DeepLearning.ai  DeepLearningSpecialization [点击查看](https://www.coursera.org/account/accomplishments/specialization/DXYEKURQDVKA)

### Java系

- Spring
- SpringBoot
- SpringCloud

### RDB

- MySQL
- SQLServer

### NoSQL

- Cassandra
- Redis
- DynamoDB
- Elasticsearch

### MQ

- Kafka
- ActiveMQ

### 前台

- Angular
- Bootstrap

### 通用
- Lambda/Serverless
- Docker/K8s
- Git/SVN
- JIRA
- 敏捷开发
- DevOps/ChatOps
- Linux
- Nginx
- ELK

**Comment by cc20101001** [comment]
本人第一次推荐工作，有家公司各方面还挺不错的。群里还有找工作的大牛吗？想进去 bat tmd 没进去，或者 bat tmd 想出来的？刚毕业没多久的小鲜肉，小仙女也可以？sea外企（新加坡公司，福利超棒，东南亚最大互联网集团），深圳 shopee 研发中心招人(核心团队)，非常不错，机会还挺好的，对标 bat tmd 福利待遇，现求贤若渴，有兴趣的可以私聊我了解一下。。大数据，产品，前后端开发，测试，ui，devops 都有需求，且量大

内推职位参考：https://app.mokahr.com/recommendation-apply/shopee

微信号:hubinwei123 备注 github 上看到的

ps: 我不是猎头也不是 hr，小开发一枚，良心推荐。。
--
