### ISSUE TITLE
ThoughtWorks 955 有真实点的消息吗？

### ISSUE THREAD

**Issue by Qianlu5110** [formulahendry/955.WLB#57]
RT

**Comment by LiuuY** [comment]
看项目，看城市

**Comment by Tony---Zhang** [comment]
大部分还是965吧~

**Comment by rsun-thoughtworks** [comment]
因为公司是分项目的，大多数的项目可以做到965。部分海外项目可以更早。

不论如何，公司文化不鼓励加班，已经足以列到名单中了。

**Comment by YuunYang** [comment]
> 大部分还是965吧~

大佬深圳office的？想问一下深圳加班吗？校招。

**Comment by chaomao** [comment]
项目忙的时候没有955，大概995吧
周六周日有大量的培训，会议，活动，出差时到客户现场也是占用个人时间，有补助，没换休
工作7年多，你说TW 955我是不信的
