### ISSUE TITLE
深圳一家外企弹性不打卡965，有需要的朋友可以找我内推

### ISSUE THREAD

**Issue by zhbitcxy** [formulahendry/955.WLB#72]
Morningsatr是一家有30多年历史的金融资讯企业，下面链接可以了解公司信息和职位信息
https://app.mokahr.com/apply/morningstar/4140?sourceToken=c0e31a0723a2cc639ee55a1aa8ac689f#/?_k=71l0ks
需要内推的可以直接把简历发我gmail邮箱

**Comment by EXcaliburQAQ** [comment]
惊现同事

**Comment by zhbitcxy** [comment]
握手

**Comment by zdbobi** [comment]
有看到招聘C# 开发 怎么联系你这边？

**Comment by zhbitcxy** [comment]
需要内推的可以把简历直接发给我的gmail邮箱

**Comment by zuopengWang** [comment]
我发现进去之前都说妹子多，进去了之后才发现都是狼。

**Comment by YuunYang** [comment]
楼主投了在牛客的校招，想问一下什么时候会面试呀

**Comment by denghuang** [comment]
链接需要绑定邮箱，打不开啊

**Comment by zhbitcxy** [comment]
> 链接需要绑定邮箱，打不开啊

谢谢提醒，链接已更新

**Comment by zhbitcxy** [comment]
> 我发现进去之前都说妹子多，进去了之后才发现都是狼。

我进来是这样，你进来也是这样

**Comment by youaresherlock** [comment]
不招Python后端人员啊?只有c#

**Comment by darknessp** [comment]
弹性就不是坑了？在家加班就不是加班了？

**Comment by TurnOffNOD** [comment]
先确定是妹子而不是女装大佬？

**Comment by zhbitcxy** [comment]
> 弹性就不是坑了？在家加班就不是加班了？

这个弹性就是正常上班时间的弹性，除了紧急线上事故，一般不用在家加班。

**Comment by zhbitcxy** [comment]
> 先确定是妹子而不是女装大佬？

原装正版妹子，因为数据分析那边是真的很多妹子哦
