### ISSUE TITLE
投票挂了QAQ 招 Python 后端 

### ISSUE THREAD

**Issue by kutoxinyi** [formulahendry/955.WLB#73]

**Comment by er567** [comment]
代朋友问下，留个jd可好

**Comment by skywalkerscott** [comment]
工作地点

**Comment by messi-yang** [comment]
全职Python后端，Go也行。

**Comment by kutoxinyi** [comment]
> 工作地点

忘记说了。。 南京

**Comment by gylidian** [comment]
南京学生路过

**Comment by kutoxinyi** [comment]
> 代朋友问下，留个jd可好
工作地点在南京，不知道能否接受。。

**Comment by kepler0308** [comment]
不留个联系方式吗= =

**Comment by kutoxinyi** [comment]
> 不留个联系方式吗= =

邮箱： 18652935264@163.com

**Comment by kutoxinyi** [comment]
> 南京学生路过

欢迎来我司实习

**Comment by kutoxinyi** [comment]
> 代朋友问下，留个jd可好

工作抵挡是南京，还考虑吗 @er567

**Comment by huisezhiyin** [comment]
哪个公司啊 我一个月前在南京找py的工作到处找不到 不得已来了苏州

**Comment by kutoxinyi** [comment]
> 哪个公司啊 我一个月前在南京找py的工作到处找不到 不得已来了苏州
@huisezhiyin 扇贝呀，而且趋势科技也有 python 吧

**Comment by huisezhiyin** [comment]
扇贝啊 之前还面过 不过当时已经又更好的选择了
趋势科技那个招了很多外包 而且趋势对学历要求太高了 总体来说工作也不是做后端的

**Comment by YuunYang** [comment]
我看到拉勾上在收应届，楼主可以内推吗？

**Comment by kutoxinyi** [comment]
> 我看到拉勾上在收应届，楼主可以内推吗？

@YuunYang 当然可以， 简历请发 18652935264@163.com

**Comment by YuunYang** [comment]
> > 我看到拉勾上在收应届，楼主可以内推吗？
> 
> @YuunYang 当然可以， 简历请发 [18652935264@163.com](mailto:18652935264@163.com)

哇，先谢谢大佬，简历我发了两遍，麻烦大佬了

**Comment by messi-yang** [comment]
社招如何操作@kutoxinyi

**Comment by youaresherlock** [comment]
huisezhiyin commented Apr 2, 2019
扇贝是外包吗？

**Comment by youaresherlock** [comment]
@huisezhiyin commented Apr 2, 2019
扇贝主营是外包吗？

**Comment by youaresherlock** [comment]
> 扇贝啊 之前还面过 不过当时已经又更好的选择了
> 趋势科技那个招了很多外包 而且趋势对学历要求太高了 总体来说工作也不是做后端的
@huisezhiyin
扇贝外包多吗?大都是外包人员吗？

**Comment by youaresherlock** [comment]
>扇贝啊 之前还面过 不过当时已经又更好的选择了
>趋势科技那个招了很多外包 而且趋势对学历要求太高了 总体来说工作也不是做后端的

@huisezhiyin
扇贝外包多吗?大都是外包人员吗？

**Comment by YuunYang** [comment]
> > 扇贝啊 之前还面过 不过当时已经又更好的选择了
> > 趋势科技那个招了很多外包 而且趋势对学历要求太高了 总体来说工作也不是做后端的
> 
> @huisezhiyin
> 扇贝外包多吗?大都是外包人员吗？

你司是外包吗？是不是外包难道不会自行在搜索引擎查询吗？就算没用过扇贝的产品，无论百度还是google排第一的也不是一个没有产品的外包企业吧。

**Comment by kutoxinyi** [comment]
> > 扇贝啊 之前还面过 不过当时已经又更好的选择了
> > 趋势科技那个招了很多外包 而且趋势对学历要求太高了 总体来说工作也不是做后端的
> 
> @huisezhiyin
> 扇贝外包多吗?大都是外包人员吗？

@youaresherlock 没有外包，都是自己的开发

**Comment by kutoxinyi** [comment]
> 社招如何操作@kutoxinyi

@messi-yang 可以在拉勾上直接投递，也可以把简历发给我，帮你内推
